### PR TITLE
reverse (intensity) -> invert

### PR DESCRIPTION
**Pull request by waxenegger**
following renaming efforts: https://github.com/openmicroscopy/openmicroscopy/pull/5470

TEST: dev-merge.openmicroscopy.org/webclient/ 
verify that the invert works by toggling the checkbox

### CODE REVIEW

**Comment by waxenegger** [comment]
--exclude

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#465](https://ci.openmicroscopy.org/job/iviewer-merge/465/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/465/consoleText) for more details.
Possible conflicts:
  - PR #114 dominikl 'Reverse intensity rename iviewer'
    - src/settings/channel-range.html

**Comment by jburel** [comment]
Note: 5.4. dependency

**Comment by waxenegger** [comment]
--exclude

**Comment by jburel** [comment]
``settings/settings.js`` will also need to be updated

**Comment by jburel** [comment]
no more instances of reverse
It works as expected

**Pull request merged**
