### PR TITLE
Bird's Eye View Revisited

### PR DESCRIPTION
**Pull request by waxenegger**
see: https://trello.com/c/6hC4Y0Bu/6-birds-eye-view

This PR will replace the "map" type solution bases on the ol3 Overviewmap for a more custom control that's closer to what is in the webclient.

The thumbnail is used as image, the box is not dotted and the size does not change (as was the case before - when zooming). Also, for big images tiles are not pulled in for the purpose of of the bird's eye view which can be the basis for more optimization in terms of big image tile loading.

### CODE REVIEW

**Comment by waxenegger** [comment]
--exclude

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#583](https://ci.openmicroscopy.org/job/iviewer-merge/583/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/583/consoleText) for more details.
Possible conflicts:
  - PR #129 waxenegger 'ol3-upgrade to 4.4.2'
    - ol3-viewer/src/ome/ol3/Viewer.js
    - ol3-viewer/src/ome/ol3/controls/BirdsEye.js
  - PR #130 waxenegger 'Tile size increase'
    - ol3-viewer/src/ome/ol3/Viewer.js

--conflicts

**Comment by waxenegger** [comment]
--exclude

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#587](https://ci.openmicroscopy.org/job/iviewer-merge/587/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/587/consoleText) for more details.
Possible conflicts:
  - PR #130 waxenegger 'Tile size increase'
    - ol3-viewer/src/ome/ol3/Viewer.js
  - PR #135 waxenegger 'Intensity Query - On/Off Toggle in Control'
    - src/settings/settings.js

--conflicts

**Comment by waxenegger** [comment]
--exclude

**Comment by waxenegger** [comment]
--exclude

**Comment by will-moore** [comment]
This all seems to be working nicely as described:
 - No tiles for birds-eye
 - Doesn't move
 - Red line looks good

Good to merge 👍

**Pull request merged**
