### PR TITLE
cowfish review patch

### PR DESCRIPTION
**Pull request by waxenegger**
https://github.com/openmicroscopy/openmicroscopy/pull/5082 expects reverse intensity to be in the maps parameter of the image request. any request in the older format is not well received in a sense that even channel start/end values seem to be ignored and the ever same image is served.

to remedy this an make review of channel related PRs possible again (e.g. https://github.com/ome/omero-iviewer/pull/30} this is temporary patch that can be easily excluded again (if not needed).

Note: https://github.com/ome/omero-iviewer/pull/25 needed to be excluded temporarily

### CODE REVIEW

**Comment by will-moore** [comment]
@waxenegger I don't think https://github.com/openmicroscopy/openmicroscopy/pull/5082 requires ```maps``` to be in query string. Certainly works fine without when I'm testing it locally.
And http://web-dev-merge.openmicroscopy.org/webclient/render_image/56754/30/0/?c=1|159:1070$0000FF,-2|51:997$00FF00,3|2:4415$FF0000,-4|1:6542$FF0000 is rendering OK (user-3)

**Comment by will-moore** [comment]
@waxenegger You need to remove the ```-r``` old flags from the query string, now that they are replaced by ```?maps```.

**Comment by waxenegger** [comment]
Yes I just quickly removed the r flags and while I was at it added the ?maps param.
For now this is a mere means to see the images load. There would be quite a few more changes in other places to adopt the  url format after your codomain. So regard it a temporary "review" fix simply...I intend to do the actual work once your PR is merged in a different one. J-M said I should hold off with a full integration the other day when we talked about it.

**Comment by will-moore** [comment]
I'm seeing lots of 404 errors from cowfish logs just now. Don't know which PR / what the problem is. 

Referrer: https://cowfish.openmicroscopy.org/webtrial/omero_iviewer/9443/
Requested URL: /webtrial/webgateway/render_image_region/9443/14/0/?region=256,256,256,256&c=1%7C0:65535$0000FF,2%7C0:65535$FF0000&maps=[%7B%22reverse%22:%7B%22enabled%22:false%7D%7D,%7B%22reverse%22:%7B%22enabled%22:false%7D%7D]&m=c&p=normal&q=0.9
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
IP address: 134.36.66.8

**Comment by waxenegger** [comment]
I take it that you mean the server logs or do you mean the dev tools show that? I suspect these image requests are a result of a timed-out session, in fact I suspect they might be from me looking at the user agent string. I mentioned it in here, I think it happened to Jean Marie. Actually comparing ips could confirm that perhaps: https://github.com/ome/omero-iviewer/pull/30.

I have to check also whether one gets a 404 in that case, I cannot remember right now. All I know is that using cowfish and also locally I don't experience any tiles/images missing when using iviewer and, inevitably I would have to with 404s. The only time I missed them was the session timeout.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#138](https://ci.openmicroscopy.org/job/iviewer-merge/138/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/138/consoleText) for more details.
Possible conflicts:
  - PR #25 waxenegger 'retrieve untiled images in one go if dimensions don't exceed 1kx1k'
    - ol3-viewer/src/ome/ol3/source/Image.js

**Comment by waxenegger** [comment]
is replaced with a permanent solution: https://github.com/ome/omero-iviewer/pull/44

**Pull request closed without merging**
