### PR TITLE
Aurelia Components Upgrade - incl. Webpack

### PR DESCRIPTION
**Pull request by waxenegger**
upgraded aurelia components (previous release versions were over a year old).
upgraded babel core and loader but left plugins (caused issue with transpilation/binding).

bumped webpack to version 2.

added necessary changes to webpack configs (Aurelia Webpack Plugin).

discovered 2 async bugs when testing, putting safeguards in place.

Note on the side: The dev server configuration (npm run dev) was updated too, but couldn't be used before the update already due to it relying on a remote omero server instance (which does not contain the plugin level calls that are required in the present codebase). But further down the track (shifting calls to server/web api, as well as adding cors support) it can hopefully be used again...

### CODE REVIEW

**Comment by waxenegger** [comment]
--exclude

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#412](https://ci.openmicroscopy.org/job/iviewer-merge/412/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/412/consoleText) for more details.
Possible conflicts:
  - PR #102 waxenegger 'roi count'
    - src/regions/regions-list.js

**Comment by waxenegger** [comment]
--exclude

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#441](https://ci.openmicroscopy.org/job/iviewer-merge/441/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/441/consoleText) for more details.
Possible conflicts:
  - PR #102 waxenegger 'roi count'
    - src/regions/regions-list.js
  - Upstream changes
    - src/regions/regions-list.js

**Comment by jburel** [comment]
No side effect noticed so time to merge

**Pull request merged**
