### PR TITLE
iviewer setup - image info request & regions request safeguard while pending

### PR DESCRIPTION
**Pull request by waxenegger**
The strategy for an iviewer setup is to hand over the already requested regions data when calling addRegions() on the embedded ol3 viewer such as to avoid a second request.

This strategy is now also employed for the image info which is handed over to the embedded iviewer at construction time. 

That way the setup will work for standalone as well as embedded (iviewer).

Moreover, for longer requests, the ready flag proved to be an insufficient safeguard against multiple regions requests (switching back and forth between rois and other tabs). This is fixed in this PR.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#312](https://ci.openmicroscopy.org/job/iviewer-merge/312/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/312/consoleText) for more details.
Possible conflicts:
  - PR #63 waxenegger 'Apps Name'
    - ol3-viewer/src/ome/ol3/Viewer.js
    - src/viewers/ol3-viewer.js
  - PR #72 waxenegger 'delete rois immediately (after dialog popup)'
    - ol3-viewer/src/ome/ol3/Viewer.js
    - src/viewers/ol3-viewer.js

**Comment by waxenegger** [comment]
-- exclude

**Comment by jburel** [comment]
Tested locally the second call in ``ol3-viewer/src/ome/ol3/source/Regions.js`` is no longer happening when selecting the tab i.e. only one call to load the rois

**Comment by jburel** [comment]
Second test:
 * Select the rois tab. Rois are loaded
 * Go back to another tab e.g. Info
 * Back to ROIs tab. Rois are not loaded. This is good

We may want to have a refresh/reload button. I will create a card since it is not for this PR nor this version

**Comment by jburel** [comment]
tested on web-dev-merge.
Everything is working 
Thanks

**Pull request merged**
