### PR TITLE
Aurelia update

### PR DESCRIPTION
**Pull request by will-moore**
See https://github.com/ome/omero-iviewer/pull/413 which fails when we update `aurelia-framework: 1.4.1`.

In this PR I'm trying an incremental approach of updating `aurelia-framework: 1.2.0` (the highest which avoids the errors on PR above), then update other dependencies to see if that allows updating of  `aurelia-framework` to latest....

### CODE REVIEW

**Comment by will-moore** [comment]
At this point, everything is still working...

**Comment by will-moore** [comment]
At this point, everything seems to be working fine...

**Comment by will-moore** [comment]
With that commit, I see...

```
Unhandled rejection Error: Invalid resource path [function Compose(element, container, compositionEngine, viewSlot, viewResources, taskQueue) {
    this.activationStrategy = ActivationStrategy.InvokeLifecycle;
    this.element = element;
    this.container = container;
    this.compositionEngine = compositionEngine;
    this.viewSlot = viewSlot;
    this.viewResources = viewResources;
    this.taskQueue = taskQueue;
    this.currentController = null;
    this.currentViewModel = null;
    this.changes = Object.create(null);  }]. Resources must be specified as relative module IDs.
    at FrameworkConfiguration.globalResources (webpack-internal:///aurelia-framework:764:15)
    at Module.configure (webpack-internal:///aurelia-templating-resources:2370:10)
    at eval (webpack-internal:///aurelia-framework:621:34)From previous event:
    at _loadPlugin (webpack-internal:///aurelia-framework:619:40)
    at eval (webpack-internal:///aurelia-framework:612:14)From previous event:
    at loadPlugin (webpack-internal:///aurelia-framework:611:73)
    at next (webpack-internal:///aurelia-framework:890:18)From previous event:
    at next (webpack-internal:///aurelia-framework:890:54)
    at eval (webpack-internal:///aurelia-framework:897:14)From previous event:
    at FrameworkConfiguration.apply (webpack-internal:///aurelia-framework:881:42)
    at Aurelia.start (webpack-internal:///aurelia-framework:462:37)
    at eval (webpack-internal:///./src/main.js:70:11)
    at eval (webpack-internal:///./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js:128:12)From previous event:
    at bootstrap (webpack-internal:///./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js:127:24)
    at eval (webpack-internal:///./src/main.js:66:71)
    at ./src/main.js (http://localhost:8080/bundle.js:4771:1)
    at __webpack_require__ (http://localhost:8080/bundle.js:727:30)
    at fn (http://localhost:8080/bundle.js:101:20)
    at 0 (http://localhost:8080/bundle.js:5289:18)
    at __webpack_require__ (http://localhost:8080/bundle.js:727:30)
    at http://localhost:8080/bundle.js:794:37
    at http://localhost:8080/bundle.js:797:10
```

**Comment by will-moore** [comment]
Having reverted and update individual libs, before the last commit, everything looked good, but with that commit I see the same error again:

```
Unhandled rejection Error: Invalid resource path [function Compose(element, container, compositionEngine, viewSlot, viewResources, taskQueue) {
    this.activationStrategy = ActivationStrategy.InvokeLifecycle;
    this.element = element;
```

**Comment by will-moore** [comment]
Before the last commit, it works OK.
The last commit includes an indirect bump of `aurelia-binding 1.7.1 -> 2.0.0` which includes breaking changes. 
Changelog: https://github.com/aurelia/binding/blob/master/doc/CHANGELOG.md#200-2018-05-09
"Removed lexer and merged into Parser. Up to 10x expression parse perf improvements."

**Comment by will-moore** [comment]
I thought that the last commit there (which works OK) included `aurelia-binding 2.5.4`, and so might allow bumping of `aurelia-templating-resources to 1.7.0`, but no. That failed (not committed).

**Comment by will-moore** [comment]
Confirmed that this PR is merged into https://github.com/ome/omero-iviewer/compare/master...snoopycrimecop:omero-iviewer:merge_ci today and that iviewer is working on merge-ci (not checked Console for errors yet etc)

**Comment by will-moore** [comment]
@jburel - This is conflicting with a bunch of other dependency bumps - I'm pretty happy with it. Just tested a bit more and no errors in the console.
OK to merge?

**Comment by jburel** [comment]
Ok i will do a final check to see if i get errors in the console

**Comment by jburel** [comment]
I have on "deprecated" message in the console
```
window.webkitStorageInfo is deprecated. Please use standardized navigator.storage instead.
```
but I don't think it is related to the upgrade

**Comment by jburel** [comment]
When selecting the move arrow in rois panel
Screenshot 2022-11-25 at 16 13 02

**Comment by jburel** [comment]
@will-moore did you get a chance to look at the latest report? As you indicated this PR is conflicting with some dependencies upgrade.

**Comment by will-moore** [comment]
@jburel I'm pretty sure those `Canvas2D` warnings are not related to the Aurelia upgrade.
The canvas is managed by OpenLayers. Warning has link to https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

**Comment by jburel** [comment]
Thanks for checking.
I didn't notice any other problem.

**Pull request merged**
