### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by jburel**
Prep for release 
cc @sbesson @waxenegger

### CODE REVIEW

**Comment by jburel** [comment]
where are the questions?

**Comment by sbesson** [comment]
Apologies @jburel, I managed to save my review without the associated inline comments. The two questions were:

- for the first item, should we mention import and acquisition dates as both are supported
- for the last item and generally, would it be useful to specify which version of Openlayers is used?

**Comment by jburel** [comment]
@sbesson adjusted

**Comment by jburel** [comment]
https://github.com/openmicroscopy/www.openmicroscopy.org/pull/159 has been merged

Merging to prep release

**Pull request merged**
