### PR TITLE
rendering settings - floating number images

### PR DESCRIPTION
**Pull request by waxenegger**
see: https://trello.com/c/2MKvXiqH/9-floating-point-images

### CODE REVIEW

**Comment by jburel** [comment]
I have imported few floating images under user-1, project "float-images"
 * The text boxes next to the slider are usually too small to display the values
 * there are differences in the values displayed between insight and iviewer (see screenshot)
float-user1-77455

**Comment by waxenegger** [comment]
@jburel I have to check that, at first I suspected that the exponential representation for rounding was the issue (which comes highly recommended) but when I downloaded and imported the file locally I got the same numbers as insight. I did see, however that web-dev-merge shows different ....
local_float

**Comment by waxenegger** [comment]
ok the solutions seems straight-forward. I did a merge-iviewer to check for conflicts but a deploy was never done after that so web-dev is not up-to-date just yet.

**Comment by jburel** [comment]
same user
http://web-dev-merge.openmicroscopy.org/iviewer/77509/?dataset=19203 
has a very small range i.e. -0.3 +0.3
This cannot be manipulated with slider
Compare with insight for expected behaviour

**Comment by waxenegger** [comment]
@jburel not sure what the heck is going on. Downloaded original and, again, no problem locally. I'll try a redeploy again, maybe closing/reopening PR or something .....

**Comment by waxenegger** [comment]
Ok something's not kosher, here, either locally (but then I fail to see how I can get the desired behavior - I'd rather be lead to believe I'd get the wrong), or on the server.

@jburel Perhaps you could try this locally just to get a better impression of what is wrong...

**Comment by jburel** [comment]
It works much better now 
small issue
http://web-dev-merge.openmicroscopy.org/iviewer/77507/?dataset=19203
The interval is correct and matches insight
but when you move the left knob of the slider, the right-hand side value also changes i.e. initial ``0.03`` then moves to ``0.029``

**Comment by jburel** [comment]
This looks much better. It works fine.

**Pull request merged**
