### PR TITLE
Roi ordering

### PR DESCRIPTION
**Pull request by jburel**
In this PR
Order shapes in the tables by z and t

cc @pwalczysko @waxenegger 

https://trello.com/c/GqokGSWB/31-feedback

### CODE REVIEW

**Comment by waxenegger** [comment]
@jburel we cannot just convert the map to an array for sorting purposes.

there is more code, the map is central to roi and shapes. it's a map based access to get by id (some hash map access underneath (browser specific), we'll lose the fast query  which is used in lots of places for select, delete, modify, etc. I doubt that as is everything is going to work....there are corresponding gets ....
with arrays we get a linear scan count performance for those operations, there has to be another solution ....

**Comment by jburel** [comment]
I just realised that when checking the selection.
Closing for now

**Comment by waxenegger** [comment]
To be honest, for now, the easiest way would be to get the sort into the query. the map should unlike hash  maps in java guarantee order so the cheapest option is to somehow add it to the sql. That said I'm not sure what options I have with marshal...

**Comment by waxenegger** [comment]
hang on, what am I saying, we can query ourselves ....

**Comment by jburel** [comment]
Use tmp map

**Comment by jburel** [comment]
replaced https://github.com/ome/omero-iviewer/pull/71 since for some reasons I cannot re-open the PR

**Pull request closed without merging**
