### PR TITLE
Support ?collapse_left/right and ?full_page=true

### LINKED ISSUE #480: Open maximised view as default
Mentioned in https://forum.image.sc/t/omero-web-configuration/98844

Open the full-screen image as default when clicking on thumbnail in omero-web. Possibly can be treated as a subtopic under the [iviewer settings issue](https://github.com/ome/omero-iviewer/issues/282) ?

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #480.

Adds support for query parameters to hide the left/right panels and show the image viewer full-page.

Try adding these parameters to the iviewer URL:
 - `?collapse_left=true`
 - `?collapse_right=true`
 - `?full_page=true`.  // does both of the above
 
Screenshot 2024-08-23 at 16 03 21

### CODE REVIEW

**Comment by pwalczysko** [comment]
@Jcarlosmiguel Would this ^^^ proposed solution solve your problem ? https://forum.image.sc/t/omero-web-configuration/98844/3 - i.e. would you know how to use the parameters in the url for your moodle app ?

**Comment by pwalczysko** [comment]
wfm with 

https://merge-ci.openmicroscopy.org/web/webclient/img_detail/4815/?dataset=2069&full_page=true
https://merge-ci.openmicroscopy.org/web/webclient/img_detail/4815/?dataset=2069&collapse_right=true
https://merge-ci.openmicroscopy.org/web/webclient/img_detail/4815/?dataset=2069&collapse_left=true

As discussed with @will-moore , there we should add some documentation of this feature.

**Review by pwalczysko — CHANGES_REQUESTED** [review]
Please explain the best tactics on documenting this feature. Otherwise wfm

**Comment by pwalczysko** [comment]
> That is exactly what I am looking for. Please, let me know when it will be implemented.

Great, as you see, we are in process of testing and wrapping up. Just bear with us please. Thanks for the feedback.

**Comment by will-moore** [comment]
Apologies for the delay on this. Added docs to the README - see https://github.com/will-moore/omero-iviewer/tree/full_page_initialParams?tab=readme-ov-file#supported-urls

**Comment by will-moore** [comment]
@Jcarlosmiguel - this feature was included in the recently released omero-iviewer 0.15.0

**Comment by Jcarlosmiguel** [comment]
I've updated my omero web (in docker compose) and it shows that OMERO.iViewer is running the Version: 0.16.0. Unfortunately, I don't see any changes with the addition of the commands at the end as suggested.
Note: I am so sorry, I was just adding without replacing the dataset portion. It works!

**Pull request merged**
