### PR TITLE
Tile size increase

### PR DESCRIPTION
**Pull request by waxenegger**
As part of some more investigation into the problem described in https://trello.com/c/lWWQS0Vg/4-server-side-load this PR can help to reduce problems. It relies on: https://github.com/openmicroscopy/openmicroscopy/pull/5542

This in only one step in the right direction, there are other reasons/causes for a larger number of tile requests and therefore higher server load. Problem is that in order to address them an iviewer alone solution does not suffice.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#530](https://ci.openmicroscopy.org/job/iviewer-merge/530/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/530/consoleText) for more details.
Possible conflicts:
  - PR #117 waxenegger 'Shape Stats'
    - src/viewers/ol3-viewer.js
  - PR #118 waxenegger 'reverse (intensity) -> invert'
    - ol3-viewer/src/ome/ol3/source/Image.js
  - PR #120 waxenegger 'Multiple Viewer Mode'
    - src/app/right-hand-panel.js
    - src/events/events.js
    - src/viewers/ol3-viewer.js

--conflicts

**Comment by waxenegger** [comment]
--exclude

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#583](https://ci.openmicroscopy.org/job/iviewer-merge/583/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/583/consoleText) for more details.
Possible conflicts:
  - PR #129 waxenegger 'ol3-upgrade to 4.4.2'
    - ol3-viewer/src/ome/ol3/source/Image.js

--conflicts

**Comment by waxenegger** [comment]
--exclude

**Comment by waxenegger** [comment]
--exclude

**Comment by jburel** [comment]
Tested iviewer with and without https://github.com/openmicroscopy/openmicroscopy/pull/5542 in
The implementation can handle both cases

**Comment by waxenegger** [comment]
--exclude

**Comment by will-moore** [comment]
This has caused a couple of issues described at https://trello.com/c/AdRIcaBJ/37-viewing-large-non-tiled-image-fails

**Pull request merged**
