### PR TITLE
apps name

### PR DESCRIPTION
**Pull request by jburel**
Add missing "apps" file

### CODE REVIEW

**Comment by waxenegger** [comment]
just testing whether this PR had an impact on cowfish ...

--exclude

**Comment by jburel** [comment]
@waxenegger: will look at the other settings

**Comment by jburel** [comment]
typo again!!

**Comment by jburel** [comment]
Removed ``exclude`` label

**Comment by jburel** [comment]
@waxenegger: everything is now working 
https://ci.openmicroscopy.org/view/Web/job/WEB-DEV-trial-deploy/135/

**Comment by jburel** [comment]
--exclude

**Comment by waxenegger** [comment]
@jburel just as a recall to have it documented here. The app.py label will necessitate changes with urls again because it does determine the url for the app BUT at the same time not change the static path for the urls resources. For that matter I strongly propose a consistent strategy/name. It is not ideal to have 5 or more things extracted/injected/reverse lookup to get the app "going". While the general prefix are absolutely necessary for install/runtime I don't see the same dynamic need/nature for the app name so I wish we could decide and keep it.

**Comment by jburel** [comment]
only re-opened so we have all elements for discussion
this PR is excluded

**Comment by jburel** [comment]
Closing this PR, @waxenegger will cherry-pick the commits

**Pull request closed without merging**
