### PR TITLE
Rois tab ui reshuffle and styling

### PR DESCRIPTION
**Pull request by waxenegger**
see: https://github.com/openmicroscopy/design/issues/75

- roi/shapes table: rearranged columns, border transparent instead of black
- delete is now a button (not dropdown) and next to edit dropdown acting like other edit widgets on selection
- show roi toggle was already visually removed in https://github.com/ome/omero-iviewer/pull/55 but now internal flag was removed and along with it a refactoring was done
- all entries in the rois table will be hidden by a checkbox on the header
- spacing for drawing menu icons was altered to give more space between select and rest of icons
- although not rois tab related the remaining code for the scalbar toggle got removed (after: https://github.com/ome/omero-iviewer/pull/54)
- 3 fixes: delete of multiple shapes, modify circle ignoring attachment, no canvas redraw on panel collapse
- rois backend request made on demand (first click on tab)
- change of default selection style and fill color

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#252](https://ci.openmicroscopy.org/job/iviewer-merge/252/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/252/consoleText) for more details.
Possible conflicts:
  - PR #50 waxenegger 'Luts - png follow up'
    - src/utils/constants.js

**Comment by waxenegger** [comment]
--exclude

until https://github.com/ome/omero-iviewer/pull/50 has been merged.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#266](https://ci.openmicroscopy.org/job/iviewer-merge/266/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/266/consoleText) for more details.
Possible conflicts:
  - PR #56 waxenegger 'OL3 style changes for controls (esp. zoom)'
    - src/css/app.css

**Comment by waxenegger** [comment]
--exclude

**Comment by waxenegger** [comment]
@jburel and @will-moore:

I'm going to list this PR for review despite the inline comment edit not being in there. That's something I wanted to discuss again since it would behave differently (acts on multiple selection actions at the moment), would have different (font) size/length in terms of input field for the row and last but not least only work if I disallowed selection of a row along the comment column.

But there is already enough in this PR to justify a review and there is another one waiting for the channel settings (https://github.com/ome/omero-iviewer/pull/58) for which I'm going to have to touch css again.

**Comment by will-moore** [comment]
- ROI table looks good
- Delete working as expected
- Show/hide toggles are behaving fine, Show/hide ALL is good too.
- Layout of drawing icons looks nice.
- ROIs are only loaded when the ROIs tab is selected
- Default stroke/fill colours are yellow/transparent as expected.

Functionality is all good ;).
Ready to merge for me.

**Comment by jburel** [comment]
If I click ``Edit>Select All``, the UI is removed from the ROIs tab.

**Comment by waxenegger** [comment]
@jburel the last commit should fix that. seems we noticed that about the same time.

**Comment by jburel** [comment]
The problem is now fixed. Merging

**Pull request merged**
