### PR TITLE
Info css tweaks

### PR DESCRIPTION
**Pull request by will-moore**
Try to improve looks for Info tab.

First shot, so far:

screen shot 2018-02-08 at 13 36 44

### CODE REVIEW

**Comment by will-moore** [comment]
I got a bit carried away and made a lot more css changes.
But travis is failing and I somehow seem to have broken the right panel in Firefox, so I'll close until I work out what's going on.
Currently looking like this (in Chrome)!

screen shot 2018-02-08 at 23 59 44
screen shot 2018-02-09 at 00 00 07

**Comment by waxenegger** [comment]
@will-moore  the travis issue is very likely not something related to this PR.

The info tab is looking much nice. Noticed 2 side-effects:

- the roi listing header (without background for the header the row underneath is visible) and the text comment icon from the row above seemed to have slipped down
image

- the controls overlapping for multi-viewer - in the case where the z slider reduces the available width:
image

**Comment by waxenegger** [comment]
@jburel I failed to get the details on the travis error again (a while ago I could fetch the log but closed it again) but I believe it was having trouble with the test runner, karma. could be that it the location has changed or the npm install failed, not sure, would have to see the logs again which for some reason I don't get at the moment...

**Comment by jburel** [comment]
I will have a look at it today

**Comment by will-moore** [comment]
@waxenegger I fixed the ROI table header and channels/scroll bar issues.
The overlapping controls for multi-view mode is already an issue without this PR (I see it on web-dev-merge today without this PR merged). Maybe the default size for new windows needs to be a little bigger?

**Comment by jburel** [comment]
@waxenegger @will-moore The failure is due to a change in test-infra. Change required to run the mapr-test
Looking into it

**Comment by waxenegger** [comment]
@will-moore if the controls placement and dimensions remain the same - and dimension wise they are already at their minimum length - extending the width at least is probably unavoidable. The coordinate box needs quite a bit of space but that's a result of catering for big images with long coordinates, the size of the font being big and writing out "X","Y" explicitly (the latter 2 having been requested). The only other idea as I said is to rearrange the placement, something like this:
image

The buttons row in the settings panel wraps at the moment when the scroll bar is present:
image

**Comment by jburel** [comment]
Note that I do not have any failure when I run locally
``.omero/docker app``

**Comment by will-moore** [comment]
With those last commits, if there's no Open-with options, we don't show the ```Open with:`` since it looked like "Open with Image info".

screen shot 2018-02-13 at 15 42 46

**Comment by jburel** [comment]
@will-moore https://github.com/ome/omero-iviewer/pull/170 fixing travis has been merged
you may want to merge develop to have travis green again

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#661](https://ci.openmicroscopy.org/job/iviewer-merge/661/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/661/consoleText) for more details.
Possible conflicts:
  - PR #151 jburel 'Multi view follow up'
    - css/app.css
  - PR #161 waxenegger 'Roi Table - multiple select'
    - css/app.css

--conflicts

**Comment by rgozim** [comment]
Instead of using browser specific css rules, could we possibly add [ _autoprefixer_](autoprefixer) to the webpack config instead?

**Comment by waxenegger** [comment]
At the moment I'm tempted to say that we'd end up with more prefixes in the css than is. Then again I'm not a css purist, I find css "bulky" as is (and at times cumbersome) so the few cases in the app.css (the ol3.css is more or less taken from ol3 sources) don't bother me too much. 

Either way something like autoprefixer could be run as a preparation step (maybe before cleancss) as part of the build.

**Comment by rgozim** [comment]
@waxenegger maybe should think about using scss instead of css if you find it bulky (which I do too), but I guess that's a topic for a different pull request.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#663](https://ci.openmicroscopy.org/job/iviewer-merge/663/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/663/consoleText) for more details.
Possible conflicts:
  - PR #161 waxenegger 'Roi Table - multiple select'
    - css/app.css
  - Upstream changes
    - css/app.css

--conflicts

**Comment by will-moore** [comment]
Hopefully fixed conflicts. To check conflicts are resolved OK, check T-slider in normal and multi-view mode.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#665](https://ci.openmicroscopy.org/job/iviewer-merge/665/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/665/consoleText) for more details.
Possible conflicts:
  - PR #166 waxenegger 'opening multiple images with double click'
    - src/app/index.html

--conflicts

**Comment by waxenegger** [comment]
@will-moore I noticed something with the collapse/expand click of the right hand panel and thought at first the jquery PR could have caused it but can rule that out now. It's very likely that one of the css changes in here (maybe flex stuff, maybe something else) are causing that behavior. It seems that the with each collapse/expand the width gets smaller and the logic in terms of remembering/restoring width has not been touched. So I'm guessing the evaluation of the width of the right-hand-panel produces different values (smaller ones each time).

**Pull request merged**
