### PR TITLE
channel settings ui refactoring, styling & bugfixing/improvements

### PR DESCRIPTION
**Pull request by waxenegger**
see: https://github.com/openmicroscopy/design/issues/75

- https://trello.com/c/02NvAiA8/27-settings-tab
- https://trello.com/c/brhz6sX0/26-size-of-tab
- scalebar always on top of other ol3 controls
- channel buttons converted to button group incl. drop-down for colors
- cherry-picked all commits from https://github.com/ome/omero-iviewer/pull/59
- only center if roi that has been clicked on in table is out of view
- mac shortcuts
- int -> rgba padding fix
- drawing mode abort on table interaction

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#263](https://ci.openmicroscopy.org/job/iviewer-merge/263/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/263/consoleText) for more details.
Possible conflicts:
  - PR #56 waxenegger 'OL3 style changes for controls (esp. zoom)'
    - src/css/app.css
  - PR #57 waxenegger 'Rois tab ui reshuffle and styling'
    - src/css/app.css

**Comment by waxenegger** [comment]
--exclude

**Comment by will-moore** [comment]
Pushed some more commits to #59 for cherry-picking.

**Comment by jburel** [comment]
Selection in table/switch mode works. This is better I think

**Comment by jburel** [comment]
Could you add copyright in the various javascript files?

**Comment by will-moore** [comment]
All seems to be looking good and working fine for me.

**Comment by jburel** [comment]
Merging
We can add copyright in js file in a follow up PR.

**Pull request merged**
