### PR TITLE
T slider with visibility: hidden blocks scalebar and birdeye view interaction

### PR DESCRIPTION
**Pull request by waxenegger**
see: https://trello.com/c/GqokGSWB/31-feedback

Due to the hidden t slider being in the dom layout still with absolute placement it 'obscured' the ui controls underneath (in terms of mouse events). Using css 'display' instead of 'visibility' should fix that.

TEST: Check that the birdeye collapse (toggle) button in the bottom right hand corner of the viewport can be clicked and toggles the birdeye visibility. Check that the scalbar can be grabbed and dragged anywhere in the viewport (before it was only moveable under the t-slider element)
Note: This problem actually only showed in images that had no t-slider/time points but it's recommended that you check all 3 possiblilies: no sliders (z/t), one z slider (no t), one 1-slider (no z), just to confirma that there are no layout side-effects.

### CODE REVIEW

**Comment by will-moore** [comment]
All working fine. Good to merge.

**Comment by jburel** [comment]
This looks like a side effect
now we have "time" info on the z-slider tooltip when moving the slider's knob
e.g. user-1 http://web-dev-merge.openmicroscopy.org/iviewer/9442/?dataset=1457

**Comment by waxenegger** [comment]
@jburel not a side-effect, just never discovered ;-)
same code for t/z, in that case there's a difference...

**Comment by jburel** [comment]
so that's a feature :-)

**Comment by waxenegger** [comment]
@jburel yes. it was a hidden feature of of the other PR so to speak ;-)

**Comment by jburel** [comment]
Everything works as expected now.
Merging

**Pull request merged**
