### PR TITLE
Changelog 0.11.0

### PR DESCRIPTION
**Pull request by sbesson**
Captures all the PRs currently merged and proposed for inclusion in the next minor release.
Suggestions on better wording welcome.

### CODE REVIEW

**Comment by will-moore** [comment]
Looks good 👍

**Comment by will-moore** [comment]
Just found https://github.com/ome/omero-iviewer/pull/372 which has been tested and fixes a user-reported bug.
Would be good to consider that for release. cc @jburel

**Comment by sbesson** [comment]
While constructing this changelog, I looked at https://github.com/ome/omero-iviewer/pull/372 and was wondering whether it would be a candidate for this release. But from the last comment it looks like it opened a wider discussion which needs to be resolved about the indexing.

**Comment by jburel** [comment]
I will not include it until we sort out the old viewer url.
Having 2 styles within the same framework will be extremely confusing.

**Comment by sbesson** [comment]
Understood, I'll go ahead for `0.11.0` as it should unlock some upcoming IDR submission and leave the discussion to continue on  #372

**Pull request merged**
