### PR TITLE
Viewer infra

### PR DESCRIPTION
**Pull request by jburel**
Use the new test-infra repository

The travis file will have to be updated when changes included in https://github.com/openmicroscopy/omero-test-infra/pull/3 are merged

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#639](https://ci.openmicroscopy.org/job/iviewer-merge/639/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/639/consoleText) for more details.
Possible conflicts:
  - PR #142 waxenegger 'Webpack Dev Server Setup - Reincarnated'
    - .travis.yml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#641](https://ci.openmicroscopy.org/job/iviewer-merge/641/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/641/consoleText) for more details.
Possible conflicts:
  - PR #142 waxenegger 'Webpack Dev Server Setup - Reincarnated'
    - .travis.yml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#644](https://ci.openmicroscopy.org/job/iviewer-merge/644/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/644/consoleText) for more details.
Possible conflicts:
  - PR #142 waxenegger 'Webpack Dev Server Setup - Reincarnated'
    - .travis.yml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#645](https://ci.openmicroscopy.org/job/iviewer-merge/645/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/645/consoleText) for more details.
Possible conflicts:
  - PR #142 waxenegger 'Webpack Dev Server Setup - Reincarnated'
    - .travis.yml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#646](https://ci.openmicroscopy.org/job/iviewer-merge/646/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/646/consoleText) for more details.
Possible conflicts:
  - PR #142 waxenegger 'Webpack Dev Server Setup - Reincarnated'
    - .travis.yml

--conflicts

**Comment by jburel** [comment]
@joshmoore travis is green using openmicroscopy/omero-test-infra

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
