### PR TITLE
use web api for regions request

### PR DESCRIPTION
**Pull request by waxenegger**
With the web api supporting rois there is no need any more to have similar code in the plugin view. Both methods use omero-marshal anyhow.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#346](https://ci.openmicroscopy.org/job/iviewer-merge/346/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/346/consoleText) for more details.
Possible conflicts:
  - PR #88 waxenegger 'copy & paste improvements'
    - src/model/regions_info.js
  - PR #91 waxenegger 'Refactoring, episode II (The Lookup Table Strikes Back)'
    - src/app/context.js

**Comment by waxenegger** [comment]
--exclude

**Comment by jburel** [comment]
@waxenegger the lut PR has been merged so after resolving the conflict we can remove the exclude

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#349](https://ci.openmicroscopy.org/job/iviewer-merge/349/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/349/consoleText) for more details.
Possible conflicts:
  - PR #88 waxenegger 'copy & paste improvements'
    - src/model/regions_info.js

**Comment by waxenegger** [comment]
--exclude

**Comment by jburel** [comment]
Loading of rois using the web api is working as expected 
I will update the version requirement for OMERO in https://github.com/ome/omero-iviewer/pull/87

**Pull request merged**
