### PR TITLE
showing only 10 dataset thumbnails by default

### PR DESCRIPTION
**Pull request by waxenegger**
see: https://trello.com/c/6bKLBqO5/280-todos

It's best to limit the number of thumbnails (dataset images) shown in the left hand panel, just in case one happens to have lots of images. Therefore the limit has been set to 10 with the option to show more on demand (by clicking the expand symbol/downward arrows).

TEST: https://cowfish.openmicroscopy.org/webtrial
Choose an image from a dataset that has fewer than 10 images associated. The left hand panel should not display the double down arrorw. Then choose an image from a dataset that has lots of images. 10 should be loaded by default, then 10 more each time you click the arrow.

### CODE REVIEW

**Comment by waxenegger** [comment]
--exclude

**Comment by will-moore** [comment]
This works fine.
The only problem is when I open an image that is not in the first 10 images in the Dataset. Then, the thumbnail for the viewed image is not present on the screen, so you can't move to next/previous and back to current image again etc.

I could make a small change to the ```paths_to_object``` support in webclient (where we already have the functionality to tell you which page an image is on) so that it supports a specified page_size/limit.
E.g.
```
/webclient/api/paths_to_object/?image=56797&limit=10
```
would then give you a path that included:
```
{
  "childIndex": 53,
  "type": "dataset",
  "id": 17752,
  "childPage": 6,
  "childCount": 61
},
```

**Comment by waxenegger** [comment]
ah, I see. yes that would be very useful. It's an additional call and I'd also have to implement loading more thumbnails in the "upwards" direction (before that is I suppose... - in terms of order less than) but that's not really a problem.

**Comment by will-moore** [comment]
Working nicely. Opening the correct 'page' of 10 thumbnails and allowing me to load the previous or next page.
Good to merge.

**Pull request merged**
