### PR TITLE
fix license file

### PR DESCRIPTION
**Pull request by jburel**
Fix header in the file
Nothing to test

### CODE REVIEW

**Comment by sbesson** [comment]
As per #362 should the license be moved to the root of this repository? Files in other sub-directories than `plugin` refer to it and that would fix the auto-detection by GitHub.

**Comment by jburel** [comment]
could do, the build will have to be reviewed since it is included in the manifest

**Comment by sbesson** [comment]
Understood, As suggested by @manics, proposing to move the `LICENSE` to the top-level as this is the standard layout and add a symlink pointing to `../LICENSE` to prevent changes to the build.

**Comment by joshmoore** [comment]
Or symlinking down?

**Comment by will-moore** [comment]
When browsing https://github.com/jburel/omero-iviewer/tree/license the LICENSE symlink doesn't allow you to view the LICENSE, you just see https://github.com/jburel/omero-iviewer/blob/license/LICENSE. 
So I guess it depends how "user friendly" we need this to be.
Would it be better to move the LICENSE to the top level and sym-link to it there? Apologies if this is too nit-picky?

**Comment by jburel** [comment]
It is due to the way symlinks are handled by git. 
```
Symbolic links are just another type of object in Git. Git saves the symlink (name and what it points to) but not the actual contents of the destination file/directory. When you checkout the commit, Git restores the symlink in your working directory.
```
I am reluctant to move the LICENSE up a folder and create a symlink since it will require a review of the build and we will have the same display on GitHub

**Comment by sbesson** [comment]
Merging and we will see how GitHub detects this one

**Pull request merged**
