### PR TITLE
add delete key handler

### PR DESCRIPTION
**Pull request by waxenegger**
see: https://trello.com/c/SaPar49q/19-delete-key-to-delete-rois

### CODE REVIEW

**Comment by mtbc** [comment]
Heh, I'm reminded of https://github.com/openmicroscopy/openmicroscopy/pull/3771#issuecomment-97716437!

**Comment by jburel** [comment]
@will-moore did you have a change to look at it?
I re-list on Monday

**Comment by will-moore** [comment]
Simply using the Delete key on Mac didn't work for me. I had to google to find this solution: http://osxdaily.com/2013/04/26/delete-key-mac-forward-del/
Holding down the ```fn``` key while hitting Delete worked OK.
But it should be possible to make this easier for Mac users?

Otherwise all works fine.

**Comment by waxenegger** [comment]
Can you do me a favor and tell me the keycode if you hit just the DEL key: http://keycode.info/

I'd rather solve it by additional keycode than rewrite the code to support some fn combination for the one mac exception.

**Comment by will-moore** [comment]
Yep, ```8``` 
http://keycode.info/ in nice!

**Comment by waxenegger** [comment]
Thanks. 

I'll push some commit later trying another, supposedly better approach.

**Comment by will-moore** [comment]
I used https://craig.is/killing/mice for OMERO.figure - Does everything I needed, handles various OSs, key combinations etc.

**Comment by waxenegger** [comment]
I have had a cursory glance and it uses `KeyboardEvent.which` with fallback onto `KeyboardEvent.keyCode` whereas I use the latter. From what I could gather which works better with Macs. 

But he "supposed problem" with that library as well as my solution is that both properties are deprecated. The absurdity of it is that the envisioned future solution is KeyboardEvent.code which in turn is not yet supported by all browsers: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code. So this leaves KeyboardEvent.key.

**Comment by joshmoore** [comment]
https://github.com/ome/omero-iviewer/pull/148#issuecomment-361774198

@will-moore : do any other repositories use Mousetrap? Are there any other strategies currently in use in OME repositories?

**Comment by will-moore** [comment]
@waxenegger Working fine for me now, thanks.

@joshmoore We don't use Mousetrap anywhere else. Just use ```event.which``` and ```event.keyCode``` in one or two places in webclient/webgateway.

**Comment by pwalczysko** [comment]
I will test it on Windows laptop

**Comment by pwalczysko** [comment]
Win7 laptop 

   - Firefox
   - IE
   - Chrome

The Delete key works as expected. 

On my Mac with attached Windows keyboard - both Delete and Backspace keys work.

**Pull request merged**
