### PR TITLE
Run unit test

### PR DESCRIPTION
**Pull request by jburel**
Run the unit test in travis

Check the output of the travis run. Tests should have been run and travis should be green

### CODE REVIEW

**Comment by waxenegger** [comment]
Just a remark because I thought of it:

I'm probably going to do some work in regards to not necessarily stretch the travis run. As is the ant task "unit-tests" should not depend on build-all which is overkill. Thatincludes the build of the compressed ol3-viewer yet again which is something that "npm run prod" already does and, really, the tests use the debug version only. So I'm thinking that a depend on "build-debug" then "build-all" should actually be much better but I'll still need to test that fully.

**Comment by jburel** [comment]
I agree that it is a bit overkill in its current form.
I can close this PR and we can include it in Travis after refactoring

**Comment by waxenegger** [comment]
@jburel we don't really need to close this PR. I have opened a new one: https://github.com/ome/omero-iviewer/pull/33 with just that tiny build change.

**Comment by jburel** [comment]
Closing this PR 
The change will be made in
https://github.com/ome/omero-iviewer/pull/33

**Pull request closed without merging**
