### PR TITLE
Mobile layout

### PR DESCRIPTION
**Pull request by will-moore**
Support iviewer use on mobile phones by switching the layout on a small screen to a "column" instead of a "row":
(layout should be unchanged on regular sized screens)

To test:
You can either test the layout on a small screen using a mobile phone or you can emulate one using the browser dev tools:
 - With a small screen, check that the layout is 'vertical' as shown, and the top and bottom panels can be collapsed & expanded
 - Thumbnails should still be scrollable etc. Viewer, rendering controls etc should be working.
 - On a big screen, everything should be mostly unchanged. Right panel drag-resize should still be working. Left panel resize has been removed (wasn't really doing much before).

Screenshot 2024-10-24 at 23 34 43

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#223](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/223/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/223/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#224](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/224/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/224/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#225](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/225/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/225/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#226](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/226/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/226/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#227](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/227/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/227/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#228](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/228/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/228/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#229](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/229/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/229/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#230](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/230/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/230/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#231](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/231/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/231/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#232](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/232/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/232/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#233](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/233/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/233/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#234](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/234/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/234/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#235](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/235/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/235/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#236](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/236/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/236/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#237](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/237/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/237/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#238](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/238/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/238/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#239](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/239/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/239/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#240](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/240/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/240/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#241](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/241/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/241/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#242](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/242/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/242/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#243](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/243/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/243/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#244](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/244/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/244/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#245](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/245/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/245/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#246](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/246/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/246/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#247](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/247/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/247/consoleText) for more details.
Possible conflicts:
  - PR #482 will-moore 'Support ?collapse_left/right and ?full_page=true'
    - src/utils/ui.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#248](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/248/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/248/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - src/utils/ui.js

--conflicts

**Comment by pwalczysko** [comment]
Will test tomorrow to include the last commit

**Comment by pwalczysko** [comment]
sorry, imho the last commit was not very lucky.
The new widget enabling the close/open of the bottom pane is covering the Z letter denoting the Z section slider and interfering with the top-left corner number (denoting the number of z-sections).
The situation as per the screenshot in the header of the PR is better imho.

Now:


Screenshot 2024-11-21 at 12 42 00
Screenshot 2024-11-21 at 12 41 46

**Review by pwalczysko — CHANGES_REQUESTED** [review]
https://github.com/ome/omero-iviewer/pull/488#issuecomment-2491055545

**Comment by will-moore** [comment]
@pwalczysko is this a bit better?

Screenshot 2024-11-25 at 13 09 13

**Review by pwalczysko — APPROVED** [review]

**Pull request merged**
