### PR TITLE
Ask if new/deleted/modified rois ought to be changed on image change

### PR DESCRIPTION
**Pull request by waxenegger**
see: https://trello.com/c/yyI19Pus/265-shapes-handling

a dialog comes up if the rois state has changed and the user clicks on any of the thumbnails in the left hand panel to ask if the change should be persisted.

this is a first version. a follow-up TODO after https://github.com/ome/omero-iviewer/pull/28: integrate into back/forward navigation.

### CODE REVIEW

**Comment by waxenegger** [comment]
--exclude

commit mixup ....

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#110](https://ci.openmicroscopy.org/job/iviewer-merge/110/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/110/consoleText) for more details.
Possible conflicts:
  - PR #23 waxenegger 'improved storage routine'
    - ol3-viewer/src/ome/ol3/source/Regions.js
  - PR #28 waxenegger 'left-hand thumbnail panel empty when opened image belongs to multiple datasets'
    - src/app/thumbnail-slider.js

**Comment by waxenegger** [comment]
--exclude

**Comment by waxenegger** [comment]
This is closed and its commits will be cherry-picked by https://github.com/ome/omero-iviewer/pull/23 and merged.

**Pull request closed without merging**
