### PR TITLE
Started on css styling of tabs & ROI panel

### PR DESCRIPTION
**Pull request by will-moore**
Started working on right panel css.

OK to continue this (if no-one else is doing the same work)?
May well conflict with other PRs, depending on how much I try to do.
cc @jburel @waxenegger 

I'll close this until more complete, since a partial fix of some css styles will break others.

screen shot 2017-05-05 at 16 12 19

### CODE REVIEW

**Comment by jburel** [comment]
see also https://github.com/ome/omero-iviewer/pull/57

**Comment by waxenegger** [comment]
yes let's not do work twice.

and these template/css mixed changes are difficult to merge since settings can influence each other and produce effects that one cannot anticipate by merely code reading and reasoning which should go in ...

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#275](https://ci.openmicroscopy.org/job/iviewer-merge/275/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/275/consoleText) for more details.
Possible conflicts:
  - PR #57 waxenegger 'Rois tab ui reshuffle and styling'
    - src/css/app.css
  - PR #58 waxenegger 'channel settings ui refactoring and styling'
    - src/css/app.css

**Comment by waxenegger** [comment]
@will-moore I'm not sure if this is a successful strategy to pursue. There are things in there that were meant to be done in https://github.com/ome/omero-iviewer/pull/58 (I'm not entirely sure why I bothered opening, describing that PR and working on it so that now 2 people can work on the same things and it's obviously going to clash as well)

The disabled color setting is used in code as well and needs to be removed from the code as well. In general a thorough code search is recommended before removing classes. It will be pretty unclear for some html elements such as the roi table that people shouldn't work with it  when drawing for instance (and they cannot actually) by taking off the style that indicates that.

I'm not entirely sure why the css restyling couldn't not wait until this PR at least has been merged. The other (https://github.com/ome/omero-iviewer/pull/58) we could have discussed a strategy as well so as to not get into each others way.

**Comment by jburel** [comment]
Let's try to synchronize effort otherwise we will waste too much time
Let's go over the tickets tomorrow to avoid such situation.
Better approach is to open a PR against @waxenegger PR so he can merge them

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#276](https://ci.openmicroscopy.org/job/iviewer-merge/276/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/276/consoleText) for more details.
Possible conflicts:
  - PR #57 waxenegger 'Rois tab ui reshuffle and styling'
    - src/css/app.css
  - PR #58 waxenegger 'channel settings ui refactoring and styling'
    - src/css/app.css

**Comment by waxenegger** [comment]
@jburel I would prefer a cherry-picking method to sync PRs. It doesn't have to be my PR necessarily but it'd be a good way of avoiding 2 parties working on the same (and conflicts).

We should sync this one and https://github.com/ome/omero-iviewer/pull/58 rather than https://github.com/ome/omero-iviewer/pull/57 which has already quite a few commits and been reviewed apart from the tab bug that was in there (last commit should fix that).

I know I have been a bit sloppy with my naming of PRs in that I did put in some commits that are outside of its context but I did list the changes in the description.

**Comment by jburel** [comment]
Closing this PR, @waxenegger will cherry-pick the commits

**Comment by will-moore** [comment]
Last 3 commits tidy Settings tab. @waxenegger can you look at these and cherry-pick if OK?

screen shot 2017-05-09 at 15 45 54

**Comment by will-moore** [comment]
Last 3 commits fix the buttons on the Settings and ROIs tabs to both be the same size ```.btn-sm```.
Also fixes the display of user-settings thumbnails.
@waxenegger Can you cherry-pick as needed? (I removed my last comment after force-pushing the last commit).

screen shot 2017-05-09 at 15 53 13

**Comment by waxenegger** [comment]
@will-moore thanks

**Pull request closed without merging**
