### PR TITLE
Update webpack4 etc

### PR DESCRIPTION
**Pull request by will-moore**
See https://github.com/ome/omero-plugins/pull/12

The tests, run via ```$ ant unit-tests``` fail to run because of incompatible versions of dependencies.
Many are quite out of date now. This updates them to latest versions, including webpack 4.

To test:
 - Travis should be green
 - iviewer should still work! Should work on IE11 (if it did before)

### CODE REVIEW

**Comment by will-moore** [comment]
Seems we are missing https://merge-ci.openmicroscopy.org/web/webclient/img_detail/18188/css/images/collapse-left.png and collapse-right.png

**Comment by will-moore** [comment]
Last commit should fix the images in the collapse-left/right icons. To test, check that left and right columns still collapse left/right (and can be resized with dragging as before).

**Comment by jburel** [comment]
It will be cleaner to have 34d3b04 in a separate PR

**Comment by jburel** [comment]
* Ran ``ant unit-tests`` locally ``TOTAL: 33 SUCCESS``
* Tested on Chrome, Safari, Firefox on Mac. No regression noticed
* I cannot test on Windows.

**Comment by will-moore** [comment]
I tested briefly on IE yesterday and the only issue I noticed was a bug that I just fixed on https://github.com/ome/omero-iviewer/pull/245
But we can't test any other PRs until this is merged.

**Comment by jburel** [comment]
@pwalczysko will you have time today to do a quick round of testing on IE?

**Comment by pwalczysko** [comment]
Tested on IE on Win7 today. The iviewer on merge-ci works as expected: Many ROIs, drawing of ROIs, multi-z and t images, rotation, save viewport as png, projections tested.

All works fine.

Ready to merge FMPOV

**Comment by will-moore** [comment]
@jburel Good to merge now?

**Comment by jburel** [comment]
Merging so we can move unlock other PRs. If we noticed some side effects, they will be fixed in follow up PRs.

**Pull request merged**
