### PR TITLE
Upgrade build system to use aurelia-cli

### PR DESCRIPTION
**Pull request by rgozim**
--exclude

### CODE REVIEW

**Comment by sbesson** [comment]
Still some conflicts. Following up this morning discussion, are there changes here that would be valuable for inclusion in the `test61` deployment before we test OMERO.iviewer as the default viewer against all IDR datasets /cc @jburel

**Comment by jburel** [comment]
There is still some work to do to run the tests
No something for ``test61``

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#3](https://security-ci.openmicroscopy.org/job/OMERO-plugins-push/3/). See the [console output](https://security-ci.openmicroscopy.org/job/OMERO-plugins-push/3/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - plugin/omero_iviewer/iviewer_settings.py
    - src/viewers/viewer/globals.js
    - src/viewers/viewer/interaction/Rotate.js
    - src/viewers/viewer/source/Image.js
    - src/viewers/viewer/utils/Conversion.js
    - src/viewers/viewer/utils/Misc.js
    - src/viewers/viewer/utils/Net.js
    - src/viewers/viewer/utils/Regions.js
    - src/viewers/viewer/utils/Style.js
    - src/viewers/viewer/utils/Transform.js
    - test/unit/viewer.js
  - Upstream changes
    - package.json
    - build.xml
    - ol3-viewer/src/ome/ol3/utils/Misc.js
    - ol3-viewer/src/ome/ol3/utils/Conversion.js
    - webpack.dev.config.js
    - .gitignore
    - prepare_build.sh
    - src/app/context.js
    - ol3-viewer/src/ome/ol3/utils/Net.js
    - webpack.prod.config.js
    - ol3-viewer/src/ome/ol3/utils/Transform.js
    - ol3-viewer/src/ome/ol3/globals.js

--conflicts

**Comment by jburel** [comment]
Closing this PR. We can cherry-pick when we work again on that part

**Pull request closed without merging**
