### PR TITLE
export channel name

### PR DESCRIPTION
**Pull request by jburel**
Use channel label instead of index

to test:
 * open an image
 * Select rois
 * export
 * check that the channel's label is displayed instead of the index

See https://trello.com/c/86NGl6mO/26-iviewer-export-cvs-channels-name

### CODE REVIEW

**Comment by mtbc** [comment]
This works okay even if there is a comma in the channel name?

**Comment by jburel** [comment]
I have not tried it. I do not think that will be the "real" case unless the user decides to edit the channel name and introduce comma which does not make much sense.

**Comment by mtbc** [comment]
Okay. Wasn't sure if there's some generic utility method already handy for escaping strings for CSVs.

**Comment by jburel** [comment]
@mtbc I will have a look

**Comment by jburel** [comment]
We could replace "comma" by "dot" since we could have value`` 617,0`` 
this could also be the case for the stats (this was requested for insight)

**Comment by pwalczysko** [comment]
I am afraid, the Export from the iviewer ROIs is not working on web-dev-merge today at all. It just does not produce any excel sheet to download, instead, after some time, the image gets refreshed and the Settings tab gets selected. 

Will probably need some investigation.

**Comment by jburel** [comment]
@pwalczysko sorry about that it should be fixed now. I will trigger a build when travis is gree

**Comment by will-moore** [comment]
This is working fine for me. Good to merge.

**Pull request merged**
