### PR TITLE
openlayers upgrade

### PR DESCRIPTION
**Pull request by waxenegger**
upgraded to latest version 4.0.1 (https://github.com/openlayers/openlayers/releases/).

TEST: The jsunit tests have been run as part of the build but don't cover everything of course. The vast majority of the changes relate to constant renames, they relate to code that deals with rendering images and rois interaction So it's best to use cowfish and go through the rendering settings (e.g. channels and luts, etc) and roi interactions (draw, modify, translate) to make sure that things haven't been adversely affected.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#138](https://ci.openmicroscopy.org/job/iviewer-merge/138/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/138/consoleText) for more details.
Possible conflicts:
  - PR #25 waxenegger 'retrieve untiled images in one go if dimensions don't exceed 1kx1k'
    - ol3-viewer/src/ome/ol3/source/Image.js
  - PR #38 waxenegger 'cowfish review patch'
    - ol3-viewer/src/ome/ol3/source/Image.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#140](https://ci.openmicroscopy.org/job/iviewer-merge/140/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/140/consoleText) for more details.
Possible conflicts:
  - PR #25 waxenegger 'retrieve untiled images in one go if dimensions don't exceed 1kx1k'
    - ol3-viewer/src/ome/ol3/source/Image.js

**Comment by waxenegger** [comment]
--exclude 

to give https://github.com/ome/omero-iviewer/pull/25 a chance to be reviewed

**Comment by jburel** [comment]
Do you want to follow the same rules for babel dependencies?

**Comment by jburel** [comment]
Discussed with @waxenegger today, we will keep the ``caret`` for babel

**Pull request merged**
