### PR TITLE
opening multiple images with double click

### PR DESCRIPTION
**Pull request by waxenegger**
see also: https://trello.com/c/BFCxWDcW/24-to-discuss-multiview-design-issue-81

Double clicking on the thumbnail will open up a new image in multi view mode. From then on one can continue double clicking to add new image windows, or single click which will replace the presently active/selective window/image with the chosen one. After closing all but one image iviewer reverts to single view mode.

### CODE REVIEW

**Comment by waxenegger** [comment]
--exclude

**Comment by jburel** [comment]
--exclude

**Comment by waxenegger** [comment]
@jburel might not be a bad idea to take the exclude off.

**Comment by jburel** [comment]
excluding this PR for now so we can check the layout fix
--exclude

**Comment by waxenegger** [comment]
@jburel you'll need to take off the exclude for this to go into the daily merge build :wink:

**Comment by will-moore** [comment]
This is working nicely for me. Behaves as expected for opening on double-click and browsing through images with single click.

**Pull request merged**
