### PR TITLE
OL3 style changes for controls (esp. zoom)

### PR DESCRIPTION
**Pull request by waxenegger**
see: https://github.com/openmicroscopy/design/issues/75

If there are any requests for style changes, please be as specific as possible. The css colors and styles I cannot really fully deduce from looking at the mockups only. So if the there is a preferred style and it is already in the css just point me toward it, if not just give me the color in any notation or the respective css property that should be applied. That way we avoid a guessing and back and forth.

### CODE REVIEW

**Comment by waxenegger** [comment]
--exclude

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [iviewer-merge#244](https://ci.openmicroscopy.org/job/iviewer-merge/244/). See the [console output](https://ci.openmicroscopy.org/job/iviewer-merge/244/consoleText) for more details.
Possible conflicts:
  - PR #54 waxenegger 'scalebar - increase spectrum (finer unit differentiation)'
    - src/css/ol3-viewer.css

**Comment by waxenegger** [comment]
--exclude

**Comment by will-moore** [comment]
Looking good.
It just occurred to me that we could make the controls at top-right appear to match the zoom controls a bit better, having them along the top...
E.g. these changes:
```
.ol-control button {
    height: 1.85em;
    width: 1.85em;
}
.ol-full-screen {
    right: .85em;
}
.ol-rotate {
    top: 0.5em;
    right: 3.35em;
}
.ol-overviewmap {
    right: .85em;
}
```
Will give you this:

screen shot 2017-05-03 at 11 16 46

**Comment by waxenegger** [comment]
@will-moore  I have included the css changes mentioned and altered the scalbar style.

There is a 1px margin on .class ol-scale-line-inner still. I think without it contrast is quite low but have a go yourself and remove it to see the results.

**Comment by will-moore** [comment]
Here's a slightly different look:

screen shot 2017-05-04 at 10 13 07

screen shot 2017-05-04 at 10 21 33

Maybe even slightly cleaner without any margin (no ambiguity about inner/outer length):

screen shot 2017-05-04 at 10 25 03

```
.ol-scale-line-inner {
    border-bottom: 6px solid #000;
    /--------remove: border-top: ---------/
    font-size: 12px;
    /------- remove: margin: 1px; --------/
}
```

**Comment by will-moore** [comment]
Other css changes look good.

**Comment by jburel** [comment]
the adjusted scale bar looks nice easier to find an allows to check distance between element

**Comment by will-moore** [comment]
Looks good, thanks.

**Pull request merged**
