### PR TITLE
projection slider range clearer

### LINKED ISSUE #337: RFE: draw line between sliders more strongly
For example, when I set the "pancakes" projection icon and get two *Z* sliders, it'd be helpful to see the line *in between* them drawn in black. That also helps to draw attention to the fact that another slider has appeared at all.

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #337 

To test:
 - Z slider should highlight the range between handles more clearly:

Screenshot 2020-08-27 at 16 06 41

Could possibly make the whole slider darker too? cc @pwalczysko ?

### CODE REVIEW

**Comment by jburel** [comment]
I was using it yesterday when checking the other PR and I think having only the range between the two knobs in a different color was useful.

**Comment by pwalczysko** [comment]
> Could possibly make the whole slider darker too? cc @pwalczysko ?

I would suggest rather to make a darker border around the knob(s). This is less important for the projection situation, which is now quite nice, as the slider is now highlighted well when the stack icon is clicked. But if no projection, sometimes it is difficult to find the knob on the slider.

For this PR,  I also think that is a clear improvement and happy to merge.

**Comment by jburel** [comment]
@will-moore do you want to try to make a darker boarder around the knob on that PR?
It is already an improvement. Happy to have it merge as it is if you prefer to look into it in a follow-up PR

**Comment by will-moore** [comment]
Think that looks better:

Screenshot 2020-09-18 at 16 07 17

**Comment by pwalczysko** [comment]
Checked on merge-ci.

Screen Shot 2020-09-22 at 11 29 43
Screen Shot 2020-09-22 at 11 29 52


Also had a look on t-slidier, also looks nice, thank you

**Review by pwalczysko — APPROVED** [review]

**Comment by will-moore** [comment]
@jburel If you're happy with this, can you merge please? Thanks.

**Comment by jburel** [comment]
Thanks. Looks good.

**Pull request merged**
